### ISSUE TITLE
custom.bootstrap.less isn't created on build & download (

### ISSUE THREAD

**Issue by a4xrbj1** [perak/kitchen-site#169]
I'm having difficulties using the bootstrap3 theme.

I've used build & download (javascript + html) and I get the following error message in the terminal:

    While processing files with flemay:less-autoprefixer (for target web.browser):
    client/styles/styles/styles.less:1: Unknown import: /client/styles/framework/bootstrap3/custom.bootstrap.less

I've checked and the file "custom.bootstrap.less" isn't in the downloaded zip file. As I'm just in my second day trying to learn frontend development I'm not able to solve this myself, help is appreciated.

**Comment by perak** [comment]
Hi @a4xrbj1 

typing from my mobile phone. please check/search other (closed) issues - other people reported the same problem. Trick is that file is created automatically when you start app for the first time, but too late and meteor reports the missing file. If you waitfew seconds, you'll see that meteor will restart automaticaly and no more errors will be shown in this and in any future sessions.

My plan is to change nemo64: bootstrap package (or to simply include file instead waiting it to be auto-generated).

**Comment by a4xrbj1** [comment]
Hi @perak 

that's unfortunately not the case. It doesn't refresh, just shows this error. I've also started completely from scratch with a new app, selected only the useraccount template and it gives me the same error message right from the start (I've deleted everything inside the project folder and also used what I downloaded).

That's very frustrating that even without changing anything and just creating an app I run into an issue that I can't solve (with my capabilities). It should be easy repeat that same behavior/error

**Comment by perak** [comment]
hum... I'll check is it something new as son as I reach my computer...

**Comment by a4xrbj1** [comment]
"My plan is to change nemo64: bootstrap package (or to simply include file instead waiting it to be auto-generated)."

I'll second that move. Everywhere on the web I find the same recommendation to this problem. It's not a MeteorKitchen specific one but rather one with the package manager in Meteor, see here: https://github.com/simison/bootstrap3-less/issues/30

**Comment by perak** [comment]
@a4xrbj1 I just made new minimal application, build & download, unzip downloaded file, started the app and it works as expected - initially it shows error, but file is automatically created after few seconds, meteor restarts and everything is going fine.

Screenshot: 
![bootstrap-error](https://cloud.githubusercontent.com/assets/5630814/10878616/36a672c6-814f-11e5-9d5a-d3fa56fe33a6.png)

Now...

- What operating system and version are you running?
- What version of meteor you have installed (type: `meteor --version`)

**Comment by a4xrbj1** [comment]
I did the same and it doesn't reload automatically (or refreshes).

Meteor 1.2.1
Mac OSX 10.10.5 Yosemite

**Comment by perak** [comment]
OK, I've sent you missing files via e-mail. Your program will work now, but that's not the solution - other user maybe experiencing the same issue but didn't reported.

I'll include these files in next version of meteor-kitchen (hopefully before the end of this week).

Thanks for reporting the issue! :+1:

**Comment by perak** [comment]
@a4xrbj1 btw, you can copy missing files into `~/.meteor-kitchen/templates/ui/bootstrap3/bootstrap3/` and meteor-kitchen will automatically copy them into correct location in every future build (that's actually what I'll do in the next version - files will be included there in official distribution).

**Comment by adnoh** [comment]
anything new about this? same problem here with a template project and with a minimal project.
Linux / Meteor 1.2.1 / Meteorkitchen 0.9.57 - I've testest with "Build locally"

**Comment by perak** [comment]
This is already fixed. What is your `meteor-kitchen --version` ?

**Comment by perak** [comment]
Ah, I see 0.9.57 . Strange!

**Comment by fahmipriadi** [comment]
I'm using meteor-kitchen 0.9.68 and meteor 1.4.1.1, and still experiencing the same issue. Is there any solution?

**Comment by fahmipriadi** [comment]
I finally able to run the example after changing my server OS from CentOS to Debian. I still dont know what's wrong anyway.

**Comment by perak** [comment]
@fahmipriadi strange. This bug is fixed long time ago and I didn't experienced it for a while (and nobody else complains).

However... I am testing on CentOS 6 often (using CentOS in VM to compile meteor-kitchen binary) and it behaves normally. How I can reproduce that?

**Comment by fahmipriadi** [comment]
@perak I was using CentOS 7. Perhaps there are compatibility issues at CentOS 7? I'm gonna try to reproduce the issue some other time. For the time being, i'm gonna use Debian.

**Comment by egbertomonteiro** [comment]
I'm having the same difficulties using Centos 7.

**Comment by perak** [comment]
@egbertomonteiro what is your `meteor-kitchen --version` ?

**Comment by the4tress** [comment]
I am also having the same issue with CentOS 7.

**Comment by perak** [comment]
@the4tress I'll try to reproduce and fix this. Installing CentOS 7...

**Comment by Luq16** [comment]
@perak 
I having this error. Could yould advise me how to get pass it. Thanks

" While processing files with less (for target web.browser):
   client/lib/styles.less:1: Unknown import: /client/styles/framework/bootstrap3/custom.bootstrap.less"

**Comment by perak** [comment]
@Luq16 

- what is your `meteor-kitchen --version` ?
- does it work normally if you build application into new directory?

**Comment by Luq16** [comment]
@perak 
Thank you. Now working. I started all over again. Possible I might have made some mistakes. Thank you.
